
[style]ToggleButton.selectionButton=\
  arc:30;\
  borderWidth:0;\
  background:null;\
  selectedBackground:#ffeaa6;\
  hoverBackground:#fbeec3;\
  pressedBackground:#9c8c59

TableHeader.separatorColor = #42d7f5
# TableHeader.bottomSeparatorColor = #48f542